### ISSUE TITLE
Install & Enable excercise2 nbextension in virtualenv

### ISSUE THREAD

**Issue by tclose** [MonashBI/nipype_arcana_workshop#10]
Some of the notebooks use this Notebook contributor extension

https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/exercise/readme.html

which I have been able to enable for my user account by running the following

```bash
$ jupyter contrib nbextension install --user
$ jupyter nbextension enable exercise2/main
```

Could you install and enable it within the virtualenv so it is active for all users by default (i.e. without the `--user` flag)

**Comment by ozej8y** [comment]
Installed for the python virtual env using

jupyter contrib nbextension install --sys-prefix
jupyter nbextension enable exercise2/main

Can you please verify its working as expected ?

**Comment by tclose** [comment]
Thanks Jay, yes it appears to be working. Although could go to the 'Nodes' notebook in the Nipype Basics section and confirm that you see a 'show/hide solution' button in the exercise section at the bottom just to make sure I am not seeing my local installation (I am pretty sure I deleted but just want to check)

**Comment by ozej8y** [comment]
Yes, I can see the show/hide solution buttons.

**Comment by tclose** [comment]
Great, thanks
