### ISSUE TITLE
Downgrade matplotlib to v2.2.4

### ISSUE THREAD

**Issue by tclose** [MonashBI/nipype_arcana_workshop#11]
One of the figures errors in the visualisation notebook due to 'NotImplementedError'. From StackExchange it seems that downgrading matplotlib to v2 should fix the problem

**Comment by ozej8y** [comment]
pip uninstall matplotlib && pip install matplotlib==2.2.4

This downgraded matplotlib, but resulted in this error.

ERROR: pingouin 0.2.9 has requirement matplotlib>=3.0.2, but you'll have matplotlib 2.2.4 which is incompatible.
Installing collected packages: matplotlib
Successfully installed matplotlib-2.2.4

I'm not sure of the impact this will have. Please advise.

**Comment by tclose** [comment]
Okay, can you downgrade to

pingouin==0.2.4
matplotlib==3.0.3

then?

**Comment by tclose** [comment]
Actually, scratch that. I think that will cause more problems than it solves. Maybe just upgrade matplotlib to 3.0.2 and see if that works

**Comment by ozej8y** [comment]
Already done:
pip uninstall pingouin && pip install pingouin==0.2.4

This uninstalled matplotlib 2.2.4 and installed 3.1.1

How would you like me to proceed ?

**Comment by tclose** [comment]
Can you upgrade Pingouin to 0.2.9 again and matplotlib to 3.0.2?

**Comment by tclose** [comment]
0.2.9 is the latest version

**Comment by ozej8y** [comment]
Pingouin now at 0.2.9
Matplotlib now at 3.0.2

**Comment by tclose** [comment]
Cool, working now too
