### ISSUE TITLE
Add SPM12 module to neuro-workshop

### ISSUE THREAD

**Issue by tclose** [MonashBI/nipype_arcana_workshop#12]
One of the notebooks requires SPM12, but the latest version installed on M3 works with Matlab2018a not Matlab2019a used by the workshop.

Could you either install SPM12 for Matlab2019a or downgrade the Matlab version in the workshop module to 2018a, and then add SPM12 to the workshop module

**Comment by ozej8y** [comment]
The latest release of SPM12 is for Matlab 2018a. :)

I have downgraded Matlab in the workshop module to 2018a  and added in SPM12.

**Comment by tclose** [comment]
Great, working now
