### ISSUE TITLE
Fix conflict issue between Octave and Neuro-Workshop installation

### ISSUE THREAD

**Issue by tclose** [MonashBI/nipype_arcana_workshop#4]
Loading the neuro-workshop at the same time as the octave module causes an error

`/usr/lib/x86_64-linux-gnu/octave/4.2.2/exec/x86_64-pc-linux-gnu/octave-gui: symbol lookup error: /usr/lib/x86_64-linux-gnu/libblas.so.3: undefined symbol: sgemv_thread_n`

**Comment by ozej8y** [comment]
This error is due to conflict with the octave module and the fsl/6.0.1 module.

**Comment by ozej8y** [comment]
Conflict resolved. octave added into the neuro-workshop module.
