### ISSUE TITLE
Install VSCode/VSCodium

### ISSUE THREAD

**Issue by tclose** [MonashBI/nipype_arcana_workshop#5]
Please install VSCode or VSCodium as an application in the CVL

**Comment by ozej8y** [comment]
Good news:

module load vscode/.1.39.2

To execute, then run 'code'

Let me know how it goes and I'll make it public by removing the "."

**Comment by tclose** [comment]
Great thanks it looks good :)

Could you please install `pylint` in the neuro-workshop virtualenv so it is accessible in vscode if you have the neuro-workshop loaded.

Maybe add the vscode module to the neuro-workshop module for good measure too.

Thanks

**Comment by ozej8y** [comment]
Pylint added to the virtual env.
VScode added to the module.

Vscode module made public.

**Comment by tclose** [comment]
Thanks
